stages:
- name: Composer Install
  steps:
  - runScriptConfig:
      image: anaxexp/wordpress-php:7.1-dev-4.5.0
      shellScript: |-
        composer install -n --prefer-dist
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: wordpress-compose-example:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
