name: Composer Install
stages:
  - name: clone
    steps:
      - sourceCodeConfig:
          branch: master
          branchCondition: only
          sourceCodeCredentialId: 'user-7fnnl:c-h9jdb-github-aecwells'
          url: 'https://github.com/anaxexp/wordpress-compose.git'
  - name: build
    steps:
      - runScriptConfig:
          image: 'php:latest'
          isShell: true
          shellScript: |-
            apt-get update
            apt-get install -y --no-install-recommends git zip libsqlite3-dev zlib1g-dev
            docker-php-ext-install zip
            curl --silent --show-error https://getcomposer.org/installer | php
            ./composer.phar install -n --prefer-dist