kind: Service
apiVersion: v1
metadata:
  name: wordpress-compose-service
spec:
  selector:
    app: wordpress-compose-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-compose-example
  labels:
    app: wordpress-compose-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-compose-example
  template:
    metadata:
      labels:
        app: wordpress-compose-example
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: wordpress-compose
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
