kind: Service
apiVersion: v1
metadata:
  name: php
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    release: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      release: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        release: wordpress
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: wordpress-compose
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 9000
